### ISSUE TITLE
Can't resolve 'ApiClient'

### ISSUE THREAD

**Issue by NukeManDan** [Xooa/xooa-javascript-sdk#8]
On loading into a fresh react app  after ` npm install xooa-sdk --save`

` var XooaClient = require("xooa-sdk");`

I get:
```
./node_modules/xooa-sdk/src/index.js
Module not found: Can't resolve 'ApiClient' in '..../node_modules/xooa-sdk/src'
```

**Comment by assafx** [comment]
The current xooa-javascript-sdk release is not supported with React due to logging framework incompatibility. A newer version with native logging, that works well with React is currently under testing. We are targeting a commit already this week. This issue will be updated when done.
